# Site settings
title: Richard Erdos
description: ddbullfrog's blog
favicon: /assets/img/avatar.JPG
baseurl:
url: http://ddbullfrog.com
rss_url: /pages/atom.xml

# Build settings
markdown: kramdown

# Author settings
author:
  name: Richard Erdos
  title: Junior Front End Developer
  address: London, United Kingdom
  email: richard.erdos@me.com
  link: http://rerdos.github.io
  weibo:
  github: rerdos
  linkedin: richarderdos
  gavatar: /assets/img/avatar.JPG
  workHistory:
    - work1:
      company: MyMiniFactory
      location: London, United Kingdom
      started: 2015
      duration: July 2015
      github: https://github.com/rerdos/Assignment/
      description: AngularJS application that requests 3D objects's data from a locally provided JSON file, then apply it into a fully responsive website with a simple search option that is powered by Angular filters. Furthermore, a modal has been applied from Angular Foundation library in order to bring more interactivity to the website. Responsive design was provided by Foundation library. Bower was used in order to manage AngularJS, Foundation and Angular-foundation libraries during and after the development.
  educationHistory:
    - education1:
      organization: Northeastern University
      degree: Bachelor
      major: Software Engineering
      started: 2005
      duration: (2005 - 2009)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
  languages:
    - language1:
      name: Hungarian
      proficiency: Native
    - language2:
      name: English
      proficiency: Professional
  programmingSkills:
    - skill1:
      name: HTML
      percentage: 90%
    - skill2:
      name: CSS
      percentage: 90%
    - skill3:
      name: AngularJS
      percentage: 80%
    - skill4:
      name: jQuery
      percentage: 60%
    - skill5:
      name: SASS
      percentage: 60%
    - skill6:
      name: Bootstrap
      percentage: 50%
